### ISSUE TITLE
NoSuchMethodError: ConnectionProvider.elastic(String, Duration)

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-netty#961]
Caused by #922 #924

Reported with https://github.com/spring-cloud/spring-cloud-gateway/issues/1532

The missing methods are

```
static ConnectionProvider elastic(String name, @Nullable Duration maxIdleTime)
static ConnectionProvider fixed(String name, int maxConnections, long acquireTimeout, @Nullable Duration maxIdleTime)
```

**Comment by violetagg** [comment]
Fixed with 7c6f01f06bbf87ee60157f87445cf42d37e1dece
Will be available with the next 0.9.4.RELEASE
