### ISSUE TITLE
Getting an `NoSuchMethodError` on `Mono.otherwiseIfEmpty`

### ISSUE THREAD

**Issue by bijukunjummen** [reactor/reactor-netty#84]
Hi, I am getting this stack trace on an invocation of HttpClientOperations, looks like it still depends on an API that has been removed in reactor-core master.

```java.lang.NoSuchMethodError: 
reactor.core.publisher.Mono.otherwiseIfEmpty(Lreactor/core/publisher/Mono;)
Lreactor/core/publisher/Mono;
	
at reactor.ipc.netty.http.client.HttpClientOperations$FluxSendForm._subscribe(HttpClientOperations.java:793) ~[reactor-netty-0.6.3.BUILD-20170425.152736-54.jar:0.6.3.BUILD-SNAPSHOT]
```

**Comment by bijukunjummen** [comment]
I think you can ignore this, I can see that the project where I got this error - github.com:spring-cloud-incubator/spring-cloud-gateway.git, may be depending on reactor-core 3.1.0.* where this has been removed.

**Comment by rstoyanchev** [comment]
We started seeing this too today. I submitted https://github.com/reactor/reactor-netty/pull/83.

**Comment by rstoyanchev** [comment]
Re-opening since reactor-netty should work with reactor-core 3.1.0.
